name: continuous-integration
on: [push]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v5
      - uses: oven-sh/setup-bun@v2
      - run: uv venv
      - run: uv pip install -r requirements.txt
        working-directory: ./backend
      - name: Backend - Check Formatting
        run: uv run ruff format --check
      - name: Backend - Lint Code
        run: uv run ruff check
      - name: Backend - Run Tests
        run: uv run manage.py test
        working-directory: ./backend/portfolio
      # - name: Frontend - Lint Code
      #   run: bun lint
      # - name: Frontend - Run Tests
      #   run: bun test
